### ISSUE TITLE
Arduino 1.0 Issue with WConstants.h

### ISSUE THREAD

**Issue by iobridge** [ryowens84/EL-Escudo#1]
In Arduino 1.0-rc1, WConstants.h does not exist as referenced by Line 13 of EL_Escudo.cpp library. 

WContsants.h references Wiring.h and Wiring.h does not exist in Arduino 1.0-rc1

I was able to get the EL_Escudo.cpp library to work on both Arduino 1.0-rc1 and Arduino 22, by changing line 13 to this:
# include "wiring.c"

I am not 100% sure of the implications of that, but EL-Escudo works as expect with the noted change.

**Comment by iobridge** [comment]
Actually, in Arduino 1.0 the solution is to replace all references to "WContsants.h" or "Wiring.h" with "Arduino.h" and everything with the sketch will work as expect.

**Comment by ghost** [comment]
For me it doesn't work with replacing "WContsants.h" by "Arduino.h".
Il works with replacing "WContsants.h" by "wiring.h", and creating wiring.h in my working folder (http://www.koders.com/c/fid59E40D9A0F70172A5FF8883C25A3FFBADA963D8F.aspx)

**Comment by pkrakow** [comment]
What version of the Arduino IDE are you running?

**Comment by ghost** [comment]
1.0 (for Mac)

**Comment by pkrakow** [comment]
I'm running on a PC.  Haven't tried it on a Mac.
